# Module 2 Assessment

Welcome to your Mod 2 Assessment. You will be tested for your understanding of concepts and ability to solve problems that have been covered in class and in the curriculum.

Use any libraries you want to solve the problems in the assessment.

You will have up to two hours to complete this assessment.

The sections of the assessment are:

- SQL and Relational Databases
- Object Oriented Programming
- Accessing Data Through APIs
- HTML, CSS and Web Scraping
- Other Database Structures (MongoDB)

In [1]:
# import the necessary libraries

import requests
import json
import pandas as pd
import sqlite3

## Pokemon

### Section 1: Getting Data

In this section we'll be using PokeAPI to get data on Pokemon. Let's first define functions to get information from the API. Provided below is a URL that will get you started with the first 151 Pokemon! Run the cell below to see what we get.

In [2]:
url = 'https://pokeapi.co/api/v2/pokemon/?limit=151'
results = requests.get(url).json()['results']
results

[{'name': 'bulbasaur', 'url': 'https://pokeapi.co/api/v2/pokemon/1/'},
 {'name': 'ivysaur', 'url': 'https://pokeapi.co/api/v2/pokemon/2/'},
 {'name': 'venusaur', 'url': 'https://pokeapi.co/api/v2/pokemon/3/'},
 {'name': 'charmander', 'url': 'https://pokeapi.co/api/v2/pokemon/4/'},
 {'name': 'charmeleon', 'url': 'https://pokeapi.co/api/v2/pokemon/5/'},
 {'name': 'charizard', 'url': 'https://pokeapi.co/api/v2/pokemon/6/'},
 {'name': 'squirtle', 'url': 'https://pokeapi.co/api/v2/pokemon/7/'},
 {'name': 'wartortle', 'url': 'https://pokeapi.co/api/v2/pokemon/8/'},
 {'name': 'blastoise', 'url': 'https://pokeapi.co/api/v2/pokemon/9/'},
 {'name': 'caterpie', 'url': 'https://pokeapi.co/api/v2/pokemon/10/'},
 {'name': 'metapod', 'url': 'https://pokeapi.co/api/v2/pokemon/11/'},
 {'name': 'butterfree', 'url': 'https://pokeapi.co/api/v2/pokemon/12/'},
 {'name': 'weedle', 'url': 'https://pokeapi.co/api/v2/pokemon/13/'},
 {'name': 'kakuna', 'url': 'https://pokeapi.co/api/v2/pokemon/14/'},
 {'name': 'beedrill', 'url': 'https://pokeapi.co/api/v2/pokemon/15/'},
 {'name': 'pidgey', 'url': 'https://pokeapi.co/api/v2/pokemon/16/'},
 {'name': 'pidgeotto', 'url': 'https://pokeapi.co/api/v2/pokemon/17/'},
 {'name': 'pidgeot', 'url': 'https://pokeapi.co/api/v2/pokemon/18/'},
 {'name': 'rattata', 'url': 'https://pokeapi.co/api/v2/pokemon/19/'},
 {'name': 'raticate', 'url': 'https://pokeapi.co/api/v2/pokemon/20/'},
 {'name': 'spearow', 'url': 'https://pokeapi.co/api/v2/pokemon/21/'},
 {'name': 'fearow', 'url': 'https://pokeapi.co/api/v2/pokemon/22/'},
 {'name': 'ekans', 'url': 'https://pokeapi.co/api/v2/pokemon/23/'},
 {'name': 'arbok', 'url': 'https://pokeapi.co/api/v2/pokemon/24/'},
 {'name': 'pikachu', 'url': 'https://pokeapi.co/api/v2/pokemon/25/'},
 {'name': 'raichu', 'url': 'https://pokeapi.co/api/v2/pokemon/26/'},
 {'name': 'sandshrew', 'url': 'https://pokeapi.co/api/v2/pokemon/27/'},
 {'name': 'sandslash', 'url': 'https://pokeapi.co/api/v2/pokemon/28/'},
 {'name': 'nidoran-f', 'url': 'https://pokeapi.co/api/v2/pokemon/29/'},
 {'name': 'nidorina', 'url': 'https://pokeapi.co/api/v2/pokemon/30/'},
 {'name': 'nidoqueen', 'url': 'https://pokeapi.co/api/v2/pokemon/31/'},
 {'name': 'nidoran-m', 'url': 'https://pokeapi.co/api/v2/pokemon/32/'},
 {'name': 'nidorino', 'url': 'https://pokeapi.co/api/v2/pokemon/33/'},
 {'name': 'nidoking', 'url': 'https://pokeapi.co/api/v2/pokemon/34/'},
 {'name': 'clefairy', 'url': 'https://pokeapi.co/api/v2/pokemon/35/'},
 {'name': 'clefable', 'url': 'https://pokeapi.co/api/v2/pokemon/36/'},
 {'name': 'vulpix', 'url': 'https://pokeapi.co/api/v2/pokemon/37/'},
 {'name': 'ninetales', 'url': 'https://pokeapi.co/api/v2/pokemon/38/'},
 {'name': 'jigglypuff', 'url': 'https://pokeapi.co/api/v2/pokemon/39/'},
 {'name': 'wigglytuff', 'url': 'https://pokeapi.co/api/v2/pokemon/40/'},
 {'name': 'zubat', 'url': 'https://pokeapi.co/api/v2/pokemon/41/'},
 {'name': 'golbat', 'url': 'https://pokeapi.co/api/v2/pokemon/42/'},
 {'name': 'oddish', 'url': 'https://pokeapi.co/api/v2/pokemon/43/'},
 {'name': 'gloom', 'url': 'https://pokeapi.co/api/v2/pokemon/44/'},
 {'name': 'vileplume', 'url': 'https://pokeapi.co/api/v2/pokemon/45/'},
 {'name': 'paras', 'url': 'https://pokeapi.co/api/v2/pokemon/46/'},
 {'name': 'parasect', 'url': 'https://pokeapi.co/api/v2/pokemon/47/'},
 {'name': 'venonat', 'url': 'https://pokeapi.co/api/v2/pokemon/48/'},
 {'name': 'venomoth', 'url': 'https://pokeapi.co/api/v2/pokemon/49/'},
 {'name': 'diglett', 'url': 'https://pokeapi.co/api/v2/pokemon/50/'},
 {'name': 'dugtrio', 'url': 'https://pokeapi.co/api/v2/pokemon/51/'},
 {'name': 'meowth', 'url': 'https://pokeapi.co/api/v2/pokemon/52/'},
 {'name': 'persian', 'url': 'https://pokeapi.co/api/v2/pokemon/53/'},
 {'name': 'psyduck', 'url': 'https://pokeapi.co/api/v2/pokemon/54/'},
 {'name': 'golduck', 'url': 'https://pokeapi.co/api/v2/pokemon/55/'},
 {'name': 'mankey', 'url': 'https://pokeapi.co/api/v2/pokemon/56/'},
 {'name': 'primeape', 'url': 'https://pokeapi.co/api/v2/pokemon/57/'},
 {'name': 'growlithe', 'url': 'https://pokeapi.co/api/v2/pokemon/58/'},
 {'name': 'arcanine', 'url': 'https://pokeapi.co/api/v2/pokemon/59/'},
 {'name': 'poliwag', 'url': 'https://pokeapi.co/api/v2/pokemon/60/'},
 {'name': 'poliwhirl', 'url': 'https://pokeapi.co/api/v2/pokemon/61/'},
 {'name': 'poliwrath', 'url': 'https://pokeapi.co/api/v2/pokemon/62/'},
 {'name': 'abra', 'url': 'https://pokeapi.co/api/v2/pokemon/63/'},
 {'name': 'kadabra', 'url': 'https://pokeapi.co/api/v2/pokemon/64/'},
 {'name': 'alakazam', 'url': 'https://pokeapi.co/api/v2/pokemon/65/'},
 {'name': 'machop', 'url': 'https://pokeapi.co/api/v2/pokemon/66/'},
 {'name': 'machoke', 'url': 'https://pokeapi.co/api/v2/pokemon/67/'},
 {'name': 'machamp', 'url': 'https://pokeapi.co/api/v2/pokemon/68/'},
 {'name': 'bellsprout', 'url': 'https://pokeapi.co/api/v2/pokemon/69/'},
 {'name': 'weepinbell', 'url': 'https://pokeapi.co/api/v2/pokemon/70/'},
 {'name': 'victreebel', 'url': 'https://pokeapi.co/api/v2/pokemon/71/'},
 {'name': 'tentacool', 'url': 'https://pokeapi.co/api/v2/pokemon/72/'},
 {'name': 'tentacruel', 'url': 'https://pokeapi.co/api/v2/pokemon/73/'},
 {'name': 'geodude', 'url': 'https://pokeapi.co/api/v2/pokemon/74/'},
 {'name': 'graveler', 'url': 'https://pokeapi.co/api/v2/pokemon/75/'},
 {'name': 'golem', 'url': 'https://pokeapi.co/api/v2/pokemon/76/'},
 {'name': 'ponyta', 'url': 'https://pokeapi.co/api/v2/pokemon/77/'},
 {'name': 'rapidash', 'url': 'https://pokeapi.co/api/v2/pokemon/78/'},
 {'name': 'slowpoke', 'url': 'https://pokeapi.co/api/v2/pokemon/79/'},
 {'name': 'slowbro', 'url': 'https://pokeapi.co/api/v2/pokemon/80/'},
 {'name': 'magnemite', 'url': 'https://pokeapi.co/api/v2/pokemon/81/'},
 {'name': 'magneton', 'url': 'https://pokeapi.co/api/v2/pokemon/82/'},
 {'name': 'farfetchd', 'url': 'https://pokeapi.co/api/v2/pokemon/83/'},
 {'name': 'doduo', 'url': 'https://pokeapi.co/api/v2/pokemon/84/'},
 {'name': 'dodrio', 'url': 'https://pokeapi.co/api/v2/pokemon/85/'},
 {'name': 'seel', 'url': 'https://pokeapi.co/api/v2/pokemon/86/'},
 {'name': 'dewgong', 'url': 'https://pokeapi.co/api/v2/pokemon/87/'},
 {'name': 'grimer', 'url': 'https://pokeapi.co/api/v2/pokemon/88/'},
 {'name': 'muk', 'url': 'https://pokeapi.co/api/v2/pokemon/89/'},
 {'name': 'shellder', 'url': 'https://pokeapi.co/api/v2/pokemon/90/'},
 {'name': 'cloyster', 'url': 'https://pokeapi.co/api/v2/pokemon/91/'},
 {'name': 'gastly', 'url': 'https://pokeapi.co/api/v2/pokemon/92/'},
 {'name': 'haunter', 'url': 'https://pokeapi.co/api/v2/pokemon/93/'},
 {'name': 'gengar', 'url': 'https://pokeapi.co/api/v2/pokemon/94/'},
 {'name': 'onix', 'url': 'https://pokeapi.co/api/v2/pokemon/95/'},
 {'name': 'drowzee', 'url': 'https://pokeapi.co/api/v2/pokemon/96/'},
 {'name': 'hypno', 'url': 'https://pokeapi.co/api/v2/pokemon/97/'},
 {'name': 'krabby', 'url': 'https://pokeapi.co/api/v2/pokemon/98/'},
 {'name': 'kingler', 'url': 'https://pokeapi.co/api/v2/pokemon/99/'},
 {'name': 'voltorb', 'url': 'https://pokeapi.co/api/v2/pokemon/100/'},
 {'name': 'electrode', 'url': 'https://pokeapi.co/api/v2/pokemon/101/'},
 {'name': 'exeggcute', 'url': 'https://pokeapi.co/api/v2/pokemon/102/'},
 {'name': 'exeggutor', 'url': 'https://pokeapi.co/api/v2/pokemon/103/'},
 {'name': 'cubone', 'url': 'https://pokeapi.co/api/v2/pokemon/104/'},
 {'name': 'marowak', 'url': 'https://pokeapi.co/api/v2/pokemon/105/'},
 {'name': 'hitmonlee', 'url': 'https://pokeapi.co/api/v2/pokemon/106/'},
 {'name': 'hitmonchan', 'url': 'https://pokeapi.co/api/v2/pokemon/107/'},
 {'name': 'lickitung', 'url': 'https://pokeapi.co/api/v2/pokemon/108/'},
 {'name': 'koffing', 'url': 'https://pokeapi.co/api/v2/pokemon/109/'},
 {'name': 'weezing', 'url': 'https://pokeapi.co/api/v2/pokemon/110/'},
 {'name': 'rhyhorn', 'url': 'https://pokeapi.co/api/v2/pokemon/111/'},
 {'name': 'rhydon', 'url': 'https://pokeapi.co/api/v2/pokemon/112/'},
 {'name': 'chansey', 'url': 'https://pokeapi.co/api/v2/pokemon/113/'},
 {'name': 'tangela', 'url': 'https://pokeapi.co/api/v2/pokemon/114/'},
 {'name': 'kangaskhan', 'url': 'https://pokeapi.co/api/v2/pokemon/115/'},
 {'name': 'horsea', 'url': 'https://pokeapi.co/api/v2/pokemon/116/'},
 {'name': 'seadra', 'url': 'https://pokeapi.co/api/v2/pokemon/117/'},
 {'name': 'goldeen', 'url': 'https://pokeapi.co/api/v2/pokemon/118/'},
 {'name': 'seaking', 'url': 'https://pokeapi.co/api/v2/pokemon/119/'},
 {'name': 'staryu', 'url': 'https://pokeapi.co/api/v2/pokemon/120/'},
 {'name': 'starmie', 'url': 'https://pokeapi.co/api/v2/pokemon/121/'},
 {'name': 'mr-mime', 'url': 'https://pokeapi.co/api/v2/pokemon/122/'},
 {'name': 'scyther', 'url': 'https://pokeapi.co/api/v2/pokemon/123/'},
 {'name': 'jynx', 'url': 'https://pokeapi.co/api/v2/pokemon/124/'},
 {'name': 'electabuzz', 'url': 'https://pokeapi.co/api/v2/pokemon/125/'},
 {'name': 'magmar', 'url': 'https://pokeapi.co/api/v2/pokemon/126/'},
 {'name': 'pinsir', 'url': 'https://pokeapi.co/api/v2/pokemon/127/'},
 {'name': 'tauros', 'url': 'https://pokeapi.co/api/v2/pokemon/128/'},
 {'name': 'magikarp', 'url': 'https://pokeapi.co/api/v2/pokemon/129/'},
 {'name': 'gyarados', 'url': 'https://pokeapi.co/api/v2/pokemon/130/'},
 {'name': 'lapras', 'url': 'https://pokeapi.co/api/v2/pokemon/131/'},
 {'name': 'ditto', 'url': 'https://pokeapi.co/api/v2/pokemon/132/'},
 {'name': 'eevee', 'url': 'https://pokeapi.co/api/v2/pokemon/133/'},
 {'name': 'vaporeon', 'url': 'https://pokeapi.co/api/v2/pokemon/134/'},
 {'name': 'jolteon', 'url': 'https://pokeapi.co/api/v2/pokemon/135/'},
 {'name': 'flareon', 'url': 'https://pokeapi.co/api/v2/pokemon/136/'},
 {'name': 'porygon', 'url': 'https://pokeapi.co/api/v2/pokemon/137/'},
 {'name': 'omanyte', 'url': 'https://pokeapi.co/api/v2/pokemon/138/'},
 {'name': 'omastar', 'url': 'https://pokeapi.co/api/v2/pokemon/139/'},
 {'name': 'kabuto', 'url': 'https://pokeapi.co/api/v2/pokemon/140/'},
 {'name': 'kabutops', 'url': 'https://pokeapi.co/api/v2/pokemon/141/'},
 {'name': 'aerodactyl', 'url': 'https://pokeapi.co/api/v2/pokemon/142/'},
 {'name': 'snorlax', 'url': 'https://pokeapi.co/api/v2/pokemon/143/'},
 {'name': 'articuno', 'url': 'https://pokeapi.co/api/v2/pokemon/144/'},
 {'name': 'zapdos', 'url': 'https://pokeapi.co/api/v2/pokemon/145/'},
 {'name': 'moltres', 'url': 'https://pokeapi.co/api/v2/pokemon/146/'},
 {'name': 'dratini', 'url': 'https://pokeapi.co/api/v2/pokemon/147/'},
 {'name': 'dragonair', 'url': 'https://pokeapi.co/api/v2/pokemon/148/'},
 {'name': 'dragonite', 'url': 'https://pokeapi.co/api/v2/pokemon/149/'},
 {'name': 'mewtwo', 'url': 'https://pokeapi.co/api/v2/pokemon/150/'},
 {'name': 'mew', 'url': 'https://pokeapi.co/api/v2/pokemon/151/'}]

[Read the documentation here](https://pokeapi.co/) for information on navigating this API and use the API to obtain data to answer the following questions.

1. For any **one** Pokemon, retrive the following information in a dictionary format with the following keys:
    - ID
    - Name
    - Base experience
    - Weight
    - Height
    - Types
    - Abilities
    
For `Types` and `Abilities`, you will want to write helper functions to have each attribute just be a list of types and a list of abilities.

- i.e. `bulbasaur.types` should return `['poison', 'grass']`
    
    
2. Get the same information for the first **151** Pokemon as a list of dictionaries ordered by Pokemon ID. Print the first and last elements of the dictionary. (Hint: Use pagination)

In [3]:
""" SOLUTION: data for one Pokemon """

# helper functions for types and abilities

def typelist(types):
    result = []
    
    # iterating through the nested dict and appending to the empty list:
    
    for i in range(len(types)):
        result.append(types[i]['type']['name'])
    return result

def abilitylist(abilities):
    result = []
    
    # iterating through the nested dict and appending to the empty list:
    
    for i in range(len(abilities)):
        result.append(abilities[i]['ability']['name'])
    return result

In [4]:
def get_pokedata(url):
    
    # getting full results for one pokemon
    info = requests.get(url).json() 
    
    # list of keys with values that don't need editing
    keys = ['id', 'name', 'base_experience', 'weight', 'height'] 
    data = {k: info[k] for k in keys} # dictionary comprehension
    
    # using the two helper functions to add types and abilities
    data['types'] = typelist(info['types'])
    data['abilities'] = abilitylist(info['abilities'])
    
    return data

In [5]:
""" SOLUTION: data for 151 Pokemon """

# list comprehension to get a list of just URLs
urls = [r['url'] for r in results]

# list comprehension with the previous function to get full data
pokedata = [get_pokedata(url) for url in urls]

In [6]:
# printing first and last elements

print(pokedata[0], pokedata[-1])

{'id': 1, 'name': 'bulbasaur', 'base_experience': 64, 'weight': 69, 'height': 7, 'types': ['poison', 'grass'], 'abilities': ['chlorophyll', 'overgrow']} {'id': 151, 'name': 'mew', 'base_experience': 270, 'weight': 40, 'height': 4, 'types': ['psychic'], 'abilities': ['synchronize']}

### Section 2: Object Oriented Programming

We're going to use the data gathered in the previous section on APIs for this section on Object Oriented Programming to instantiate Pokemon objects and write instance methods.

#### Creating a Class

1. Create a class called `Pokemon` with an `__init__` method to instantiate the following attributes:
    - ID
    - Name
    - Base experience
    - Weight
    - Height
    - Types
    - Abilities
    
    
#### Instantiating Objects

2. Using the data you obtained from the API, instantiate the first, fourth and seventh Pokemon. Assign them to the variables `bulbasaur`, `charmander` and `squirtle`.

In [ ]:
# if you were unable to get the data from the API in the right format,
# uncomment the code below to access a JSON file with the list of dictionaries

# with open('data/pokemon.json') as f:  
#     pokelist = json.load(f)

In [7]:
class Pokemon:
    
    def __init__(self, ID, name, exp, weight, height, types, abilities):
        self.ID = ID
        self.name = name
        self.exp = exp
        self.weight = weight
        self.height = height
        self.types = types
        self.abilities = abilities
        
    def bmi(self):
        return (self.weight*0.1)/(self.height*0.1)**2

In [11]:
""" SOLUTION: instantiating three Pokemon """

# function to instantiate a Pokemon
def instantiate_pokemon(info):
    pokemon = Pokemon(info['id'], 
                      info['name'], 
                      info['base_experience'], 
                      info['weight'], 
                      info['height'], 
                      info['types'],
                      info['abilities'])
    return pokemon

"""
can also be done manually:

bulbasaur = Pokemon(1, 'bulbasaur', 64, 69, 7, ['poison', 'grass'], ['chlorophyll', 'overgrow'])

etc.

"""

bulbasaur = instantiate_pokemon(pokedata[0])
charmander = instantiate_pokemon(pokedata[3])
squirtle = instantiate_pokemon(pokedata[6])

In [12]:
# run this cell to test and check your code
# you may need to edit the attribute variable names if you named them differently!

def print_pokeinfo(pokemon_object):
    o = pokemon_object
    print('ID: ' + str(o.ID) + '\n' +
          'Name: ' + o.name.title() + '\n' +
          'Base experience: ' + str(o.exp) + '\n' +
          'Weight: ' + str(o.weight) + '\n' +
          'Height: ' + str(o.height) + '\n' +
          'Types: ' + str(o.types) + '\n' +
          'Abilities: ' + str(o.abilities) + '\n'
         )
    
print_pokeinfo(bulbasaur)
print_pokeinfo(ivysaur)
print_pokeinfo(venusaur)

ID: 1
Name: Bulbasaur
Base experience: 64
Weight: 69
Height: 7
Types: ['poison', 'grass']
Abilities: ['chlorophyll', 'overgrow']

ID: 4
Name: Charmander
Base experience: 62
Weight: 85
Height: 6
Types: ['fire']
Abilities: ['solar-power', 'blaze']

ID: 7
Name: Squirtle
Base experience: 63
Weight: 90
Height: 5
Types: ['water']
Abilities: ['rain-dish', 'torrent']

#### Instance Methods

3. Write an instance method within the class `Pokemon` to find the BMI of a Pokemon. BMI is defined by $\frac{weight}{height^{2}}$ with weight in **kilograms** and height in **meters**. The height and weight data of Pokemon from the API is in **decimeters** and **hectograms** respectively.


    1 decimeter = 0.1 meters
    1 hectogram = 0.1 kilograms

In [13]:
# run this cell to test and check your code
# you probably have to rerun the code to instantiate your objects

print(bulbasaur.bmi()) # 14.08
print(charmander.bmi()) # 23.61
print(squirtle.bmi()) # 36

14.081632653061222
23.611111111111104
36.0

## SQL Queries

For this section, we've put the Pokemon data into SQL tables. You won't need to use your list of dictionaries or the JSON file for this section. The schema of `pokemon.db` is as follows:

<img src="data/pokemondb.png" alt="db schema" style="width:500px;"/>

Assign your SQL queries as strings to the variables `q1`, `q2`, etc. and run the cells at the end of this section to print your results as Pandas DataFrames.

- q1: query all columns from `Pokemon` the Pokemon that have base_experience above 200
- q2: query the id, name, type1 and type2 of Pokemon that have **water** types as either their first or second type
- q3: query the average weight of Pokemon by their first type in descending order
- q4: query the Pokemon name, Pokemon type2, and what **type2** has "2xdamage" to
- q5: query the top 5 most common type1s, the minimum height, maximum height, minimum weight and maximum weight of pokemon with those type1s, and what associated type they do "0.5xdamage" to


**Important note on syntax**: use `double quotes ""` when quoting strings **within** your query and wrap the entire query in `single quotes ''` For the column titles that begin with numbers, you need to wrap the column names in double quotes.

In [15]:
cnx = sqlite3.connect('data/pokemon.db')

In [17]:
q1 = 'select * from pokemon where base_experience > 150'
pd.read_sql(q1, cnx)

     id        name  base_experience  weight  height     type1     type2
0     3    venusaur              236    1000      20     grass    poison
1     6   charizard              240     905      17      fire    flying
2     9   blastoise              239     855      16     water      None
3    12  butterfree              178     320      11       bug    flying
4    15    beedrill              178     295      10       bug    poison
5    18     pidgeot              216     395      15    normal    flying
6    22      fearow              155     380      12    normal    flying
7    24       arbok              157     650      35    poison      None
8    26      raichu              218     300       8  electric      None
9    28   sandslash              158     295      10    ground      None
10   31   nidoqueen              227     600      13    poison    ground
11   34    nidoking              227     620      14    poison    ground
12   36    clefable              217     400      13     fairy      None
13   38   ninetales              177     199      11      fire      None
14   40  wigglytuff              196     120      10    normal     fairy
15   42      golbat              159     550      16    poison    flying
16   45   vileplume              221     186      12     grass    poison
17   49    venomoth              158     125      15       bug    poison
18   53     persian              154     320      10    normal      None
19   55     golduck              175     766      17     water      None
20   57    primeape              159     320      10  fighting      None
21   59    arcanine              194    1550      19      fire      None
22   62   poliwrath              230     540      13     water  fighting
23   65    alakazam              225     480      15   psychic      None
24   68     machamp              227    1300      16  fighting      None
25   71  victreebel              221     155      17     grass    poison
26   73  tentacruel              180     550      16     water    poison
27   76       golem              223    3000      14      rock    ground
28   78    rapidash              175     950      17      fire      None
29   80     slowbro              172     785      16     water   psychic
..  ...         ...              ...     ...     ...       ...       ...
40  106   hitmonlee              159     498      15  fighting      None
41  107  hitmonchan              159     502      14  fighting      None
42  110     weezing              172      95      12    poison      None
43  112      rhydon              170    1200      19    ground      rock
44  113     chansey              395     346      11    normal      None
45  115  kangaskhan              172     800      22    normal      None
46  117      seadra              154     250      12     water      None
47  119     seaking              158     390      13     water      None
48  121     starmie              182     800      11     water   psychic
49  122     mr-mime              161     545      13   psychic     fairy
50  124        jynx              159     406      14       ice   psychic
51  125  electabuzz              172     300      11  electric      None
52  126      magmar              173     445      13      fire      None
53  127      pinsir              175     550      15       bug      None
54  128      tauros              172     884      14    normal      None
55  130    gyarados              189    2350      65     water    flying
56  131      lapras              187    2200      25     water       ice
57  134    vaporeon              184     290      10     water      None
58  135     jolteon              184     245       8  electric      None
59  136     flareon              184     250       9      fire      None
60  139     omastar              173     350      10      rock     water
61  141    kabutops              173     405      13      rock     water
62  142  aerodactyl              180     590      18      rock    flying
63  143     snorlax              189    4600      21    normal      None
64  144    articuno              261     554      17       ice    flying
65  145      zapdos              261     526      16  electric    flying
66  146     moltres              261     600      20      fire    flying
67  149   dragonite              270    2100      22    dragon    flying
68  150      mewtwo              306    1220      20   psychic      None
69  151         mew              270      40       4   psychic      None

[70 rows x 7 columns]

In [18]:
q2 = 'select id, name, type1, type2 from pokemon where type1 == "water" or type2 == "water"'
pd.read_sql(q2, cnx)

     id        name  type1     type2
0     7    squirtle  water      None
1     8   wartortle  water      None
2     9   blastoise  water      None
3    54     psyduck  water      None
4    55     golduck  water      None
5    60     poliwag  water      None
6    61   poliwhirl  water      None
7    62   poliwrath  water  fighting
8    72   tentacool  water    poison
9    73  tentacruel  water    poison
10   79    slowpoke  water   psychic
11   80     slowbro  water   psychic
12   86        seel  water      None
13   87     dewgong  water       ice
14   90    shellder  water      None
15   91    cloyster  water       ice
16   98      krabby  water      None
17   99     kingler  water      None
18  116      horsea  water      None
19  117      seadra  water      None
20  118     goldeen  water      None
21  119     seaking  water      None
22  120      staryu  water      None
23  121     starmie  water   psychic
24  129    magikarp  water      None
25  130    gyarados  water    flying
26  131      lapras  water       ice
27  134    vaporeon  water      None
28  138     omanyte   rock     water
29  139     omastar   rock     water
30  140      kabuto   rock     water
31  141    kabutops   rock     water

In [19]:
q3 = 'select type1, avg(weight) from pokemon group by type1 order by avg(weight) desc'
pd.read_sql(q3, cnx)

       type1  avg(weight)
0       rock   876.111111
1     dragon   766.000000
2      water   579.678571
3   fighting   542.857143
4    psychic   515.625000
5     normal   500.863636
6       fire   480.250000
7        ice   480.000000
8     ground   452.625000
9   electric   317.888889
10     grass   279.916667
11    poison   273.142857
12     fairy   237.500000
13       bug   229.916667
14     ghost   135.666667

In [20]:
q4 = 'select pokemon.name, type2, "2xdamage" from pokemon join types on pokemon.type2 = types.name'
pd.read_sql(q4, cnx)

          name     type2  2xdamage
0    bulbasaur    poison     grass
1      ivysaur    poison     grass
2     venusaur    poison     grass
3    charizard    flying  fighting
4   butterfree    flying  fighting
5       weedle    poison     grass
6       kakuna    poison     grass
7     beedrill    poison     grass
8       pidgey    flying  fighting
9    pidgeotto    flying  fighting
10     pidgeot    flying  fighting
11     spearow    flying  fighting
12      fearow    flying  fighting
13   nidoqueen    ground    poison
14    nidoking    ground    poison
15  jigglypuff     fairy  fighting
16  wigglytuff     fairy  fighting
17       zubat    flying  fighting
18      golbat    flying  fighting
19      oddish    poison     grass
20       gloom    poison     grass
21   vileplume    poison     grass
22       paras     grass    ground
23    parasect     grass    ground
24     venonat    poison     grass
25    venomoth    poison     grass
26   poliwrath  fighting    normal
27  bellsprout    poison     grass
28  weepinbell    poison     grass
29  victreebel    poison     grass
..         ...       ...       ...
37   magnemite     steel      rock
38    magneton     steel      rock
39   farfetchd    flying  fighting
40       doduo    flying  fighting
41      dodrio    flying  fighting
42     dewgong       ice    flying
43    cloyster       ice    flying
44      gastly    poison     grass
45     haunter    poison     grass
46      gengar    poison     grass
47        onix    ground    poison
48   exeggcute   psychic  fighting
49   exeggutor   psychic  fighting
50     rhyhorn      rock    flying
51      rhydon      rock    flying
52     starmie   psychic  fighting
53     mr-mime     fairy  fighting
54     scyther    flying  fighting
55        jynx   psychic  fighting
56    gyarados    flying  fighting
57      lapras       ice    flying
58     omanyte     water    ground
59     omastar     water    ground
60      kabuto     water    ground
61    kabutops     water    ground
62  aerodactyl    flying  fighting
63    articuno    flying  fighting
64      zapdos    flying  fighting
65     moltres    flying  fighting
66   dragonite    flying  fighting

[67 rows x 3 columns]

In [21]:
q5 = 'select type1, count(*), min(height), max(height), min(weight), max(weight), "0.5xdamage" from pokemon \
        join types on pokemon.type1 = types.name \
        group by type1 \
        order by count(*) desc limit 5'
pd.read_sql(q5, cnx)

,type1,count(*),min(height),max(height),min(weight),max(weight),0.5xdamage
0,water,28,3,65,40,2350,steel
1,normal,22,3,22,18,4600,None
2,poison,14,4,35,10,650,fighting
3,bug,12,3,15,29,560,fighting
4,fire,12,6,20,85,1550,bug